spring.application.name=sistema

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM559242
spring.datasource.password=190805
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver